version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo pre_build
  build:
    commands:
      - mvn clean prepare-package war:exploded
      - echo build
  post_build:
    commands:
      - echo post_build

artifacts:
  files:
    - deploy/**/*